// Professional DOCX generator — WordprocessingML, embedded real images, quiz callouts

function crc32(data: Uint8Array): number {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[i] = c;
  }
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) crc = table[(crc ^ data[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}
function enc(s: string) { return new TextEncoder().encode(s); }
function u16(v: number) { const b = new Uint8Array(2); b[0]=v&0xff; b[1]=(v>>8)&0xff; return b; }
function u32(v: number) { const b = new Uint8Array(4); b[0]=v&0xff; b[1]=(v>>8)&0xff; b[2]=(v>>16)&0xff; b[3]=(v>>24)&0xff; return b; }
function cat(...arr: Uint8Array[]) {
  const total = arr.reduce((s,a)=>s+a.length,0);
  const out = new Uint8Array(total); let off = 0;
  for (const a of arr) { out.set(a,off); off+=a.length; }
  return out;
}
interface ZFile { name: string; data: Uint8Array }
function buildZip(files: ZFile[]): Uint8Array {
  const locals: Uint8Array[]=[], centrals: Uint8Array[]=[];
  let offset = 0;
  for (const f of files) {
    const nm=enc(f.name), crc=crc32(f.data), sz=f.data.length;
    const lh=cat(new Uint8Array([0x50,0x4b,0x03,0x04]),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(sz),u32(sz),u16(nm.length),u16(0),nm,f.data);
    const cd=cat(new Uint8Array([0x50,0x4b,0x01,0x02]),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(sz),u32(sz),u16(nm.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nm);
    locals.push(lh); centrals.push(cd); offset+=lh.length;
  }
  const cdData=cat(...centrals);
  const eocd=cat(new Uint8Array([0x50,0x4b,0x05,0x06]),u16(0),u16(0),u16(files.length),u16(files.length),u32(cdData.length),u32(offset),u16(0));
  return cat(...locals,cdData,eocd);
}

function wEsc(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

const D = {
  indigo:  '4F46E5', indigoD: '3730A3', purple: '7C3AED',
  cyan:    '06B6D4', emerald: '10B981', amber:  'F59E0B', rose: 'EF4444',
  navy:    '0F0C29', white:   'FFFFFF', bgLight: 'EEF2FF',
  darkTxt: '1E293B', muted:   '64748B', hr:     'C7D2FE',
};
const BULLET_COLORS = [D.indigo, D.purple, D.cyan, D.emerald, D.amber, D.rose];

function cleanText(s: string): string {
  return s.replace(/\*\*(.*?)\*\*/g,'$1').replace(/\*(.*?)\*/g,'$1').replace(/`(.*?)`/g,'$1').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').trim();
}

function inlineRuns(text: string, defaultColor = D.darkTxt, defaultSz = '22'): string {
  const segs: Array<{ bold?: boolean; italic?: boolean; code?: boolean; text: string }> = [];
  let rest = text;
  while (rest.length > 0) {
    const bM = rest.match(/^\*\*(.*?)\*\*/s), iM = rest.match(/^\*(.*?)\*/s), cM = rest.match(/^`(.*?)`/s);
    if (bM) { segs.push({ bold: true, text: bM[1] }); rest = rest.slice(bM[0].length); }
    else if (iM) { segs.push({ italic: true, text: iM[1] }); rest = rest.slice(iM[0].length); }
    else if (cM) { segs.push({ code: true, text: cM[1] }); rest = rest.slice(cM[0].length); }
    else { const n = rest.search(/\*\*|\*|`/); if (n===-1) { segs.push({text:rest}); rest=''; } else { segs.push({text:rest.slice(0,n)}); rest=rest.slice(n); } }
  }
  const parts = segs.filter(s=>s.text).map(s => {
    let rPr = `<w:rPr>`;
    if (s.bold)   rPr += `<w:b/><w:color w:val="${D.indigoD}"/>`;
    else if (s.italic) rPr += `<w:i/><w:color w:val="${D.muted}"/>`;
    else if (s.code)   rPr += `<w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:color w:val="${D.indigo}"/><w:shd w:val="clear" w:color="auto" w:fill="F1F5F9"/>`;
    else rPr += `<w:color w:val="${defaultColor}"/>`;
    rPr += `<w:sz w:val="${defaultSz}"/><w:szCs w:val="${defaultSz}"/></w:rPr>`;
    return `<w:r>${rPr}<w:t xml:space="preserve">${wEsc(s.text)}</w:t></w:r>`;
  });
  return parts.join('') || `<w:r><w:rPr><w:color w:val="${defaultColor}"/><w:sz w:val="${defaultSz}"/></w:rPr><w:t xml:space="preserve">${wEsc(text)}</w:t></w:r>`;
}

interface DocImage { data: Uint8Array; ext: string; mediaName: string; rId: string; picId: number }

interface DocParagraph {
  type: 'h1'|'h2'|'h3'|'h4'|'para'|'bullet'|'numbered'|'hr'|'code'|'blank'|'image'|'quiz';
  text: string;
  bulletIdx?: number;
  imageQuery?: string;
  image?: DocImage;
}

const PLACEHOLDER_RE = /^(image|photo|picture|illustration|video|audio|animation|infographic|interactive element|speaker note|note|caption|alt text|figure|diagram|chart|graph|map|table|icon|logo|background|footer|header|source|reference|citation)\s*:/i;

function parseDoc(content: string): DocParagraph[] {
  const cleaned = content
    .replace(/\b(as an ai[^.\n]*[.\n]|as a language model[^.\n]*[.\n]|generated by ai[^.\n]*[.\n]|note: i am an ai[^.\n]*[.\n]|disclaimer:[^.\n]*[.\n])/gi, '')
    .replace(/\n{3,}/g, '\n\n');

  const lines = cleaned.split('\n');
  const result: DocParagraph[] = [];
  let bulletIdx = 0, prevWasBlank = false, inCode = false;
  const codeLines: string[] = [];

  for (const raw of lines) {
    const line = raw.trim();

    if (inCode) {
      if (line.startsWith('```')) { inCode = false; result.push({ type: 'code', text: codeLines.join('\n') }); codeLines.length = 0; }
      else codeLines.push(raw);
      continue;
    }
    if (line.startsWith('```')) { inCode = true; prevWasBlank = false; continue; }

    if (!line) {
      if (!prevWasBlank) result.push({ type: 'blank', text: '' });
      prevWasBlank = true; bulletIdx = 0; continue;
    }
    prevWasBlank = false;

    const h1 = line.match(/^#\s+(.+)/);   if (h1) { bulletIdx=0; result.push({ type:'h1', text:cleanText(h1[1]) }); continue; }
    const h2 = line.match(/^##\s+(.+)/);  if (h2) { bulletIdx=0; result.push({ type:'h2', text:cleanText(h2[1]) }); continue; }
    const h3 = line.match(/^###\s+(.+)/); if (h3) { bulletIdx=0; result.push({ type:'h3', text:cleanText(h3[1]) }); continue; }
    const h4 = line.match(/^####\s+(.+)/);if (h4) { bulletIdx=0; result.push({ type:'h4', text:cleanText(h4[1]) }); continue; }

    // ── Check for special markers ANYWHERE in the line ──
    // This handles "▸ Image: [IMAGE: ...]", "- [IMAGE: ...]", plain "[IMAGE: ...]", etc.

    // [IMAGE: query] found anywhere in line → real photo to embed
    const imgAnywhere = line.match(/\[IMAGE:\s*(.+?)\]/i);
    if (imgAnywhere) { result.push({ type: 'image', text: '', imageQuery: imgAnywhere[1].trim() }); continue; }

    // [VIDEO:] / [AUDIO:] / [ANIMATION:] → drop entirely (can't embed these)
    if (/\[(VIDEO|AUDIO|ANIMATION|INTERACTIVE):/i.test(line)) continue;

    // [QUIZ: question] found anywhere
    const qzAnywhere = line.match(/\[QUIZ:\s*(.+?)\]/i);
    if (qzAnywhere) { result.push({ type: 'quiz', text: qzAnywhere[1].trim() }); continue; }

    const stripped = line.replace(/^[-*+•▸►✦\d.]+\s*/,'').trim();

    // Legacy AI output without brackets: "Image: a photo of tigers"
    const legacyImg = stripped.match(/^image\s*:\s*(.+)/i);
    if (legacyImg) {
      const inner = legacyImg[1].match(/\[IMAGE:\s*(.+?)\]/i);
      const query = inner ? inner[1] : legacyImg[1].replace(/\[.*?\]/g,'').trim();
      if (query.length > 2) result.push({ type: 'image', text: '', imageQuery: query });
      continue;
    }

    // Legacy AI output: "Interactive element: ..." / "Quiz: ..."
    const legacyQz = stripped.match(/^(interactive element|quiz)\s*:\s*(.+)/i);
    if (legacyQz) {
      const qText = legacyQz[2].replace(/\[.*?\]/g,'').trim();
      if (qText.length > 3) result.push({ type: 'quiz', text: qText });
      continue;
    }

    if (PLACEHOLDER_RE.test(stripped)) continue;
    if (line.match(/^[-*+•▸►✦]\s+/)) { result.push({ type:'bullet', text:line.replace(/^[-*+•▸►✦]\s+/,''), bulletIdx:bulletIdx++ }); continue; }
    const numM = line.match(/^\d+\.\s+(.+)/); if (numM) { result.push({ type:'numbered', text:numM[1], bulletIdx:bulletIdx++ }); continue; }
    if (line.match(/^[-*_]{3,}$/)) { bulletIdx=0; result.push({ type:'hr', text:'' }); continue; }
    bulletIdx=0;
    result.push({ type:'para', text:line });
  }
  return result;
}

// Word inline drawing XML for an embedded image (EMU: 1 inch = 914400)
function renderImageParagraph(p: DocParagraph): string {
  if (!p.image) {
    // Failed to fetch — render a gray placeholder box with caption
    return `<w:p><w:pPr><w:shd w:val="clear" w:color="auto" w:fill="E2E8F0"/><w:spacing w:before="120" w:after="120"/><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:color w:val="${D.muted}"/><w:sz w:val="20"/><w:i/></w:rPr><w:t xml:space="preserve">&#x1F5BC; ${wEsc(p.imageQuery || 'Image')}</w:t></w:r></w:p>`;
  }
  const img = p.image;
  // 5.5" × 3.67" — fills most of the text column nicely
  const CX = 5029200, CY = 3352800;
  return `<w:p>
  <w:pPr><w:jc w:val="center"/><w:spacing w:before="120" w:after="120"/></w:pPr>
  <w:r><w:drawing>
    <wp:inline distT="0" distB="0" distL="0" distR="0" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
      <wp:extent cx="${CX}" cy="${CY}"/>
      <wp:effectExtent l="0" t="0" r="0" b="0"/>
      <wp:docPr id="${img.picId}" name="${img.mediaName}"/>
      <wp:cNvGraphicFramePr><a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/></wp:cNvGraphicFramePr>
      <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
        <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
          <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
            <pic:nvPicPr>
              <pic:cNvPr id="${img.picId}" name="${img.mediaName}"/>
              <pic:cNvPicPr><a:picLocks noChangeAspect="1" noChangeArrowheads="1"/></pic:cNvPicPr>
            </pic:nvPicPr>
            <pic:blipFill>
              <a:blip r:embed="${img.rId}"/>
              <a:stretch><a:fillRect/></a:stretch>
            </pic:blipFill>
            <pic:spPr bwMode="auto">
              <a:xfrm><a:off x="0" y="0"/><a:ext cx="${CX}" cy="${CY}"/></a:xfrm>
              <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
            </pic:spPr>
          </pic:pic>
        </a:graphicData>
      </a:graphic>
    </wp:inline>
  </w:drawing></w:r>
</w:p>`;
}

function renderParagraph(p: DocParagraph): string {
  const bColor = BULLET_COLORS[(p.bulletIdx ?? 0) % BULLET_COLORS.length];

  switch (p.type) {
    case 'image': return renderImageParagraph(p);

    case 'quiz':
      return `<w:p>
  <w:pPr>
    <w:shd w:val="clear" w:color="auto" w:fill="${D.purple}"/>
    <w:spacing w:before="160" w:after="40"/>
    <w:ind w:left="216" w:right="216"/>
    <w:pBdr><w:left w:val="single" w:sz="36" w:space="4" w:color="FDE68A"/></w:pBdr>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="FDE68A"/><w:sz w:val="20"/></w:rPr><w:t xml:space="preserve"> &#x2753; QUIZ  </w:t></w:r>
  <w:r><w:rPr><w:b/><w:color w:val="${D.white}"/><w:sz w:val="22"/></w:rPr><w:t xml:space="preserve">${wEsc(p.text)}</w:t></w:r>
</w:p>
<w:p>
  <w:pPr>
    <w:shd w:val="clear" w:color="auto" w:fill="4C1D95"/>
    <w:spacing w:before="0" w:after="160"/>
    <w:ind w:left="216" w:right="216"/>
    <w:pBdr><w:left w:val="single" w:sz="36" w:space="4" w:color="FDE68A"/></w:pBdr>
  </w:pPr>
  <w:r><w:rPr><w:color w:val="DDD6FE"/><w:sz w:val="18"/><w:i/></w:rPr><w:t xml:space="preserve"> Think about your answer before reading on...</w:t></w:r>
</w:p>`;

    case 'blank': return `<w:p><w:pPr><w:spacing w:before="60" w:after="60"/></w:pPr></w:p>`;

    case 'hr': return `<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="12" w:space="1" w:color="${D.indigo}"/></w:pBdr><w:spacing w:before="120" w:after="120"/></w:pPr></w:p>`;

    case 'h1':
      return `<w:p>
  <w:pPr>
    <w:shd w:val="clear" w:color="auto" w:fill="${D.navy}"/>
    <w:spacing w:before="240" w:after="160"/>
    <w:ind w:left="288" w:right="288"/>
    <w:pBdr><w:left w:val="single" w:sz="48" w:space="4" w:color="${D.indigo}"/></w:pBdr>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.white}"/><w:sz w:val="52"/><w:szCs w:val="52"/><w:rFonts w:ascii="Calibri Light" w:hAnsi="Calibri Light"/></w:rPr><w:t xml:space="preserve"> ${wEsc(p.text)}</w:t></w:r>
</w:p>`;

    case 'h2':
      return `<w:p>
  <w:pPr>
    <w:shd w:val="clear" w:color="auto" w:fill="${D.indigo}"/>
    <w:spacing w:before="200" w:after="120"/>
    <w:ind w:left="216" w:right="216"/>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.white}"/><w:sz w:val="40"/><w:szCs w:val="40"/><w:rFonts w:ascii="Calibri Light" w:hAnsi="Calibri Light"/></w:rPr><w:t xml:space="preserve"> ${wEsc(p.text)}</w:t></w:r>
</w:p>`;

    case 'h3':
      return `<w:p>
  <w:pPr>
    <w:shd w:val="clear" w:color="auto" w:fill="${D.bgLight}"/>
    <w:spacing w:before="160" w:after="80"/>
    <w:ind w:left="144"/>
    <w:pBdr><w:left w:val="single" w:sz="24" w:space="4" w:color="${D.purple}"/></w:pBdr>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.indigoD}"/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t xml:space="preserve"> ${wEsc(p.text)}</w:t></w:r>
</w:p>`;

    case 'h4':
      return `<w:p>
  <w:pPr>
    <w:spacing w:before="120" w:after="60"/>
    <w:pBdr><w:bottom w:val="single" w:sz="6" w:space="1" w:color="${D.hr}"/></w:pBdr>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.indigo}"/><w:sz w:val="26"/><w:szCs w:val="26"/><w:caps/></w:rPr><w:t>${wEsc(p.text)}</w:t></w:r>
</w:p>`;

    case 'bullet': {
      const odd = (p.bulletIdx ?? 0) % 2 === 0;
      return `<w:p>
  <w:pPr>
    ${odd ? `<w:shd w:val="clear" w:color="auto" w:fill="F8FAFF"/>` : ''}
    <w:spacing w:before="60" w:after="60"/>
    <w:ind w:left="576" w:hanging="360"/>
  </w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${bColor}"/><w:sz w:val="22"/></w:rPr><w:t xml:space="preserve">&#x25B8; </w:t></w:r>
  ${inlineRuns(p.text, D.darkTxt, '22')}
</w:p>`;
    }

    case 'numbered': {
      const num = (p.bulletIdx ?? 0) + 1;
      return `<w:p>
  <w:pPr><w:spacing w:before="60" w:after="60"/><w:ind w:left="576" w:hanging="360"/></w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.indigo}"/><w:sz w:val="22"/></w:rPr><w:t xml:space="preserve">${num}. </w:t></w:r>
  ${inlineRuns(p.text, D.darkTxt, '22')}
</w:p>`;
    }

    case 'code': {
      const codeLines2 = p.text.split('\n');
      return codeLines2.map((cl, li) => `<w:p>
  <w:pPr><w:shd w:val="clear" w:color="auto" w:fill="1E293B"/><w:spacing w:before="${li===0?'80':'0'}" w:after="${li===codeLines2.length-1?'80':'0'}"/><w:ind w:left="216" w:right="216"/></w:pPr>
  <w:r><w:rPr><w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/><w:color w:val="E2E8F0"/><w:sz w:val="18"/></w:rPr><w:t xml:space="preserve">${wEsc(cl || ' ')}</w:t></w:r>
</w:p>`).join('\n');
    }

    case 'para':
    default:
      return `<w:p>
  <w:pPr><w:spacing w:before="60" w:after="100"/><w:jc w:val="both"/></w:pPr>
  ${inlineRuns(p.text, D.darkTxt, '22')}
</w:p>`;
  }
}

function buildDocumentXml(paragraphs: DocParagraph[], docTitle: string): string {
  const date = new Date().toLocaleDateString('en-US', { year:'numeric', month:'long', day:'numeric' });

  const header = `<w:p>
  <w:pPr><w:shd w:val="clear" w:color="auto" w:fill="${D.navy}"/><w:spacing w:before="0" w:after="0"/><w:ind w:left="216" w:right="216"/><w:pBdr><w:left w:val="single" w:sz="48" w:space="4" w:color="${D.indigo}"/></w:pBdr></w:pPr>
  <w:r><w:rPr><w:b/><w:color w:val="${D.white}"/><w:sz w:val="32"/><w:rFonts w:ascii="Calibri Light" w:hAnsi="Calibri Light"/></w:rPr><w:t xml:space="preserve"> &#x2726; FIUS EXPORT</w:t></w:r>
</w:p>
<w:p>
  <w:pPr><w:shd w:val="clear" w:color="auto" w:fill="${D.navy}"/><w:spacing w:before="0" w:after="240"/><w:ind w:left="216" w:right="216"/><w:pBdr><w:left w:val="single" w:sz="48" w:space="4" w:color="${D.indigo}"/></w:pBdr></w:pPr>
  <w:r><w:rPr><w:color w:val="94A3B8"/><w:sz w:val="18"/></w:rPr><w:t xml:space="preserve"> ${wEsc(date)}</w:t></w:r>
</w:p>`;

  const footer = `<w:p>
  <w:pPr><w:pBdr><w:top w:val="single" w:sz="6" w:space="1" w:color="${D.indigo}"/></w:pBdr><w:spacing w:before="240" w:after="60"/></w:pPr>
  <w:r><w:rPr><w:color w:val="${D.muted}"/><w:sz w:val="16"/></w:rPr><w:t>Generated by Fius</w:t></w:r>
  <w:r><w:rPr><w:color w:val="${D.muted}"/><w:sz w:val="16"/></w:rPr><w:tab/><w:t>${wEsc(date)}</w:t></w:r>
</w:p>`;

  const body = paragraphs.map(p => renderParagraph(p)).join('\n');

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
  xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"
  xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  mc:Ignorable="w14">
  <w:body>
${header}
${body}
${footer}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1260" w:bottom="1440" w:left="1260" w:header="720" w:footer="720" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>`;
}

function buildStylesXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:cs="Calibri"/><w:sz w:val="22"/><w:szCs w:val="22"/><w:color w:val="1E293B"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="160" w:line="276" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:styleId="Normal" w:default="1"><w:name w:val="Normal"/></w:style></w:styles>`;
}

async function fetchDocImage(query: string): Promise<{ data: Uint8Array; ext: string } | null> {
  try {
    const res = await fetch('/api/fetch-image-for-export', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
      signal: AbortSignal.timeout(25000),
    });
    if (!res.ok) return null;
    const json = await res.json();
    if (!json.base64) return null;
    const binary = atob(json.base64);
    const data = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) data[i] = binary.charCodeAt(i);
    const ext = (json.mimeType || '').includes('png') ? 'png' : 'jpg';
    return { data, ext };
  } catch { return null; }
}

export async function downloadWordDoc(content: string, filename = 'fius-document') {
  // Step 1 — AI reformat
  let processedContent = content;
  try {
    const res = await fetch('/api/format-for-export', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content, type: 'docx' }),
    });
    if (res.ok) { const d = await res.json(); if (d.formatted) processedContent = d.formatted; }
  } catch { /* use original */ }

  // Step 2 — Parse
  const paragraphs = parseDoc(processedContent);
  const docTitle = paragraphs.find(p=>p.type==='h1')?.text || filename.replace(/-/g,' ');

  // Step 3 — Fetch images in parallel, assign rIds (start at rId2; rId1=styles)
  const imageParagraphs = paragraphs.filter(p => p.type === 'image' && p.imageQuery);
  let nextRId = 2, nextPicId = 1;
  await Promise.all(imageParagraphs.map(async p => {
    const img = await fetchDocImage(p.imageQuery!);
    if (img) {
      const rId = `rId${nextRId++}`;
      const picId = nextPicId++;
      const mediaName = `image${picId}.${img.ext}`;
      p.image = { ...img, rId, picId, mediaName };
    }
  }));

  // Step 4 — Build XML
  const documentXml = buildDocumentXml(paragraphs, docTitle);
  const stylesXml = buildStylesXml();

  // Step 5 — Media files
  const mediaFiles: ZFile[] = paragraphs
    .filter(p => p.image)
    .map(p => ({ name: `word/media/${p.image!.mediaName}`, data: p.image!.data }));

  const hasJpg = mediaFiles.some(f => f.name.endsWith('.jpg'));
  const hasPng = mediaFiles.some(f => f.name.endsWith('.png'));
  const imgContentTypes = [
    hasJpg ? `<Default Extension="jpg" ContentType="image/jpeg"/>` : '',
    hasJpg ? `<Default Extension="jpeg" ContentType="image/jpeg"/>` : '',
    hasPng ? `<Default Extension="png" ContentType="image/png"/>` : '',
  ].join('');

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${imgContentTypes}<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`;

  // doc.xml.rels: rId1=styles + rId2..N=images
  const imageRels = paragraphs
    .filter(p => p.image)
    .map(p => `<Relationship Id="${p.image!.rId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/${p.image!.mediaName}"/>`)
    .join('');

  const docRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${imageRels}</Relationships>`;

  // Step 6 — Build ZIP
  const files: ZFile[] = [
    { name: '[Content_Types].xml', data: enc(contentTypes) },
    { name: '_rels/.rels', data: enc(rootRels) },
    { name: 'word/document.xml', data: enc(documentXml) },
    { name: 'word/_rels/document.xml.rels', data: enc(docRels) },
    { name: 'word/styles.xml', data: enc(stylesXml) },
    ...mediaFiles,
  ];

  const zip = buildZip(files);
  const blob = new Blob([zip], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${filename}.docx`;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
