// Professional Word Document (.doc) export — Word-compatible HTML format

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function processMarkdownToHtml(content: string): string {
  // Remove AI disclaimer phrases
  let text = content
    .replace(/\b(as an ai[^.]*\.|as a language model[^.]*\.|generated by ai[^.]*\.|note: i am an ai[^.]*\.|disclaimer:[^.\n]*\.)/gi, '')
    .replace(/^\s*[\-–—]\s*$/gm, '');

  const lines = text.split('\n');
  const htmlParts: string[] = [];
  let inList = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      continue;
    }

    // H1
    const h1 = trimmed.match(/^#\s+(.+)/);
    if (h1) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      htmlParts.push(`<h1>${escapeHtml(h1[1].replace(/\*\*/g, ''))}</h1>`);
      continue;
    }

    // H2
    const h2 = trimmed.match(/^##\s+(.+)/);
    if (h2) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      htmlParts.push(`<h2>${escapeHtml(h2[1].replace(/\*\*/g, ''))}</h2>`);
      continue;
    }

    // H3
    const h3 = trimmed.match(/^###\s+(.+)/);
    if (h3) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      htmlParts.push(`<h3>${escapeHtml(h3[1].replace(/\*\*/g, ''))}</h3>`);
      continue;
    }

    // H4
    const h4 = trimmed.match(/^####\s+(.+)/);
    if (h4) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      htmlParts.push(`<h4>${escapeHtml(h4[1].replace(/\*\*/g, ''))}</h4>`);
      continue;
    }

    // Bullet
    const bullet = trimmed.match(/^[-*•▸►]\s+(.+)/);
    if (bullet) {
      if (!inList) { htmlParts.push('<ul>'); inList = true; }
      const bulletContent = formatInline(bullet[1]);
      htmlParts.push(`<li>${bulletContent}</li>`);
      continue;
    }

    // Numbered list
    const numbered = trimmed.match(/^\d+\.\s+(.+)/);
    if (numbered) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      const numContent = formatInline(numbered[1]);
      htmlParts.push(`<p class="numbered">${numContent}</p>`);
      continue;
    }

    // Code block
    if (trimmed.startsWith('```')) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      const codeLines: string[] = [];
      i++;
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        codeLines.push(escapeHtml(lines[i]));
        i++;
      }
      htmlParts.push(`<pre><code>${codeLines.join('\n')}</code></pre>`);
      continue;
    }

    // Horizontal rule
    if (trimmed.match(/^[-*_]{3,}$/)) {
      if (inList) { htmlParts.push('</ul>'); inList = false; }
      htmlParts.push('<hr/>');
      continue;
    }

    // Normal paragraph
    if (inList) { htmlParts.push('</ul>'); inList = false; }
    const para = formatInline(trimmed);
    htmlParts.push(`<p>${para}</p>`);
  }

  if (inList) htmlParts.push('</ul>');
  return htmlParts.join('\n');
}

function formatInline(text: string): string {
  return escapeHtml(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/_(.+?)_/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code>$1</code>');
}

export async function downloadWordDoc(content: string, filename = 'fius-document') {
  // Try to AI-format the content first
  let processedContent = content;
  try {
    const res = await fetch('/api/format-for-export', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content, type: 'docx' }),
    });
    if (res.ok) {
      const data = await res.json();
      if (data.formatted) processedContent = data.formatted;
    }
  } catch { /* use original if formatting fails */ }

  const bodyHtml = processMarkdownToHtml(processedContent);

  const docHtml = `
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>90</w:Zoom><w:DoNotOptimizeForBrowser/></w:WordDocument></xml><![endif]-->
  <style>
    /* === Page layout === */
    body {
      font-family: 'Calibri', 'Segoe UI', sans-serif;
      font-size: 11pt;
      color: #1E293B;
      line-height: 1.6;
      margin: 0;
      padding: 0;
      background: #ffffff;
    }

    .page {
      max-width: 750px;
      margin: 0 auto;
      padding: 60px 72px;
    }

    /* === Document header === */
    .doc-header {
      border-bottom: 4px solid #4F46E5;
      padding-bottom: 20px;
      margin-bottom: 36px;
      background: linear-gradient(135deg, #F8F8FF 0%, #EEF2FF 100%);
      padding: 24px 28px;
      border-radius: 8px;
      border-left: 6px solid #4F46E5;
    }

    .doc-header .brand {
      font-size: 10pt;
      color: #6366F1;
      font-weight: 600;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      margin-bottom: 6px;
    }

    .doc-header .doc-date {
      font-size: 9pt;
      color: #94A3B8;
      margin-top: 4px;
    }

    /* === Headings === */
    h1 {
      font-size: 22pt;
      font-weight: 700;
      color: #4F46E5;
      margin: 32px 0 12px;
      padding-bottom: 8px;
      border-bottom: 2px solid #E0E7FF;
      line-height: 1.2;
    }

    h2 {
      font-size: 16pt;
      font-weight: 700;
      color: #3730A3;
      margin: 28px 0 10px;
      padding: 8px 0 8px 14px;
      border-left: 4px solid #6366F1;
      background: linear-gradient(90deg, #EEF2FF 0%, transparent 100%);
    }

    h3 {
      font-size: 13pt;
      font-weight: 700;
      color: #1E293B;
      margin: 20px 0 8px;
      padding-left: 10px;
      border-left: 3px solid #06B6D4;
    }

    h4 {
      font-size: 11pt;
      font-weight: 700;
      color: #475569;
      margin: 16px 0 6px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    /* === Paragraphs === */
    p {
      margin: 0 0 12px;
      text-align: justify;
      color: #1E293B;
    }

    /* === Lists === */
    ul {
      list-style: none;
      padding: 0;
      margin: 8px 0 16px;
    }

    ul li {
      position: relative;
      padding: 6px 12px 6px 28px;
      margin-bottom: 4px;
      color: #1E293B;
      border-radius: 4px;
      transition: background 0.2s;
    }

    ul li::before {
      content: '▸';
      position: absolute;
      left: 10px;
      color: #6366F1;
      font-size: 10pt;
    }

    ul li:nth-child(6n+1)::before { color: #4F46E5; }
    ul li:nth-child(6n+2)::before { color: #7C3AED; }
    ul li:nth-child(6n+3)::before { color: #06B6D4; }
    ul li:nth-child(6n+4)::before { color: #10B981; }
    ul li:nth-child(6n+5)::before { color: #F59E0B; }
    ul li:nth-child(6n+6)::before { color: #F43F5E; }

    ul li:nth-child(even) {
      background-color: #F8FAFF;
    }

    /* === Numbered items === */
    p.numbered {
      padding-left: 28px;
      position: relative;
      counter-increment: list-counter;
    }

    /* === Inline code === */
    code {
      background: #F1F5F9;
      border: 1px solid #E2E8F0;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Consolas', 'Courier New', monospace;
      font-size: 9pt;
      color: #6366F1;
    }

    /* === Code blocks === */
    pre {
      background: #0F172A;
      border: 1px solid #1E293B;
      border-radius: 8px;
      padding: 16px 20px;
      overflow-x: auto;
      margin: 16px 0;
    }

    pre code {
      background: transparent;
      border: none;
      padding: 0;
      color: #E2E8F0;
      font-size: 9pt;
      line-height: 1.5;
    }

    /* === Strong / Em === */
    strong {
      color: #3730A3;
      font-weight: 700;
    }

    em {
      color: #6B7280;
      font-style: italic;
    }

    /* === Horizontal rule === */
    hr {
      border: none;
      height: 2px;
      background: linear-gradient(90deg, #4F46E5, #7C3AED, #06B6D4);
      margin: 28px 0;
      border-radius: 2px;
    }

    /* === Footer === */
    .doc-footer {
      margin-top: 48px;
      padding-top: 16px;
      border-top: 1px solid #E2E8F0;
      font-size: 8pt;
      color: #94A3B8;
      display: flex;
      justify-content: space-between;
    }

    /* === Highlight boxes === */
    .highlight-box {
      background: linear-gradient(135deg, #EEF2FF, #F0FDF4);
      border: 1px solid #C7D2FE;
      border-radius: 8px;
      padding: 16px 20px;
      margin: 16px 0;
    }

    @media print {
      body { margin: 0; padding: 0; }
      .page { padding: 20px 36px; }
      .doc-footer { position: fixed; bottom: 0; width: 100%; }
    }
  </style>
  <title>Fius Document Export</title>
</head>
<body>
  <div class="page">
    <div class="doc-header">
      <div class="brand">✦ Fius — Professional Export</div>
      <div class="doc-date">${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
    </div>

    <div class="content">
      ${bodyHtml}
    </div>

    <div class="doc-footer">
      <span>Generated by Fius</span>
      <span>${new Date().toLocaleDateString()}</span>
    </div>
  </div>
</body>
</html>`.trim();

  const blob = new Blob(['\ufeff', docHtml], {
    type: 'application/msword;charset=utf-8',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
