// Professional PPTX generator — reliable solid-fill design, no ph placeholders, no XML comments

function crc32(data: Uint8Array): number {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[i] = c;
  }
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) crc = table[(crc ^ data[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}
function enc(s: string) { return new TextEncoder().encode(s); }
function u16(v: number) { const b = new Uint8Array(2); b[0] = v & 0xff; b[1] = (v >> 8) & 0xff; return b; }
function u32(v: number) { const b = new Uint8Array(4); b[0] = v & 0xff; b[1] = (v >> 8) & 0xff; b[2] = (v >> 16) & 0xff; b[3] = (v >> 24) & 0xff; return b; }
function cat(...arr: Uint8Array[]) {
  const total = arr.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total); let off = 0;
  for (const a of arr) { out.set(a, off); off += a.length; }
  return out;
}
interface ZFile { name: string; data: Uint8Array }
function buildZip(files: ZFile[]): Uint8Array {
  const locals: Uint8Array[] = [], centrals: Uint8Array[] = [];
  let offset = 0;
  for (const f of files) {
    const nm = enc(f.name), crc = crc32(f.data), sz = f.data.length;
    const lh = cat(new Uint8Array([0x50,0x4b,0x03,0x04]),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(sz),u32(sz),u16(nm.length),u16(0),nm,f.data);
    const cd = cat(new Uint8Array([0x50,0x4b,0x01,0x02]),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(sz),u32(sz),u16(nm.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nm);
    locals.push(lh); centrals.push(cd); offset += lh.length;
  }
  const cdData = cat(...centrals);
  const eocd = cat(new Uint8Array([0x50,0x4b,0x05,0x06]),u16(0),u16(0),u16(files.length),u16(files.length),u32(cdData.length),u32(offset),u16(0));
  return cat(...locals, cdData, eocd);
}
function xEsc(s: string) {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

interface Slide { title: string; bullets: string[] }

const C = {
  navy:    '0F0C29',
  indigo:  '4F46E5',
  purple:  '7C3AED',
  cyan:    '06B6D4',
  emerald: '10B981',
  amber:   'F59E0B',
  rose:    'EF4444',
  white:   'FFFFFF',
  offWht:  'F8F8FF',
  darkTxt: '1E293B',
  muted:   '64748B',
  lightBg: 'EEF2FF',
};

const ACCENT = [C.indigo, C.purple, C.cyan, C.emerald, C.amber, C.rose];
const BULLET_COLORS = [C.indigo, C.purple, C.cyan, C.emerald, C.amber, C.rose];

function accent(i: number) { return ACCENT[i % ACCENT.length]; }

function solidShape(id: number, name: string, x: number, y: number, cx: number, cy: number, fill: string): string {
  return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${name}"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="${fill}"/></a:solidFill><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody></p:sp>`;
}

function textShape(id: number, name: string, x: number, y: number, cx: number, cy: number, anchorV: string, content: string): string {
  return `<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="${name}"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${x}" y="${y}"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr anchor="${anchorV}" wrap="square"><a:normAutofit/></a:bodyPr><a:lstStyle/>${content}</p:txBody></p:sp>`;
}

function cleanContent(content: string): string {
  return content
    .replace(/\b(as an ai[^.\n]*[.\n]|as a language model[^.\n]*[.\n]|generated by ai[^.\n]*[.\n]|note: i am an ai[^.\n]*[.\n]|disclaimer:[^.\n]*[.\n])/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function parseSlides(content: string): Slide[] {
  const cleaned = cleanContent(content);
  const lines = cleaned.split('\n');
  const slides: Slide[] = [];
  let cur: Slide | null = null;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    const hm = line.match(/^#{1,4}\s+(.+)/);
    if (hm) {
      if (cur && (cur.title || cur.bullets.length)) slides.push(cur);
      cur = { title: hm[1].replace(/\*\*/g,'').replace(/\*/g,'').trim(), bullets: [] };
    } else {
      if (!cur) cur = { title: '', bullets: [] };
      const clean = line.replace(/^[-*•▸►]\s*/,'').replace(/\*\*(.*?)\*\*/g,'$1').replace(/\*(.*?)\*/g,'$1').replace(/`(.*?)`/g,'$1').trim();
      if (clean.length > 2) cur.bullets.push(clean.slice(0, 200));
    }
  }
  if (cur && (cur.title || cur.bullets.length)) slides.push(cur);

  if (!slides.length) {
    const text = cleaned.replace(/[#*`]/g,'').trim();
    slides.push({ title: 'Presentation', bullets: text.split('\n').map(l => l.trim()).filter(Boolean).slice(0, 7) });
  }

  const out: Slide[] = [];
  for (const s of slides) {
    if (!s.title && !s.bullets.length) continue;
    if (s.bullets.length <= 6) { out.push(s); continue; }
    for (let i = 0; i < s.bullets.length; i += 6)
      out.push({ title: s.title + (i ? ' (cont.)' : ''), bullets: s.bullets.slice(i, i + 6) });
  }
  return out.slice(0, 40);
}

function makeTitleSlide(title: string, subtitle: string): string {
  const titlePara = `<a:p><a:pPr algn="l"/><a:r><a:rPr lang="en-US" sz="4000" b="1" dirty="0"><a:solidFill><a:srgbClr val="${C.white}"/></a:solidFill><a:latin typeface="Calibri Light"/></a:rPr><a:t>${xEsc(title)}</a:t></a:r></a:p>`;
  const subPara = `<a:p><a:pPr algn="l"/><a:r><a:rPr lang="en-US" sz="1800" dirty="0"><a:solidFill><a:srgbClr val="CBD5E1"/></a:solidFill><a:latin typeface="Calibri"/></a:rPr><a:t>${xEsc(subtitle)}</a:t></a:r></a:p>`;

  const shapes = [
    solidShape(10, 'BG', 0, 0, 9144000, 6858000, C.navy),
    solidShape(11, 'TopBar', 0, 0, 9144000, 190500, C.indigo),
    solidShape(12, 'BottomBar', 0, 6667500, 9144000, 190500, C.purple),
    solidShape(13, 'LeftStripe', 0, 190500, 95250, 6477000, C.indigo),
    solidShape(14, 'AccentDot1', 8000000, 500000, 500000, 500000, C.purple),
    solidShape(15, 'AccentDot2', 8200000, 5900000, 300000, 300000, C.cyan),
    solidShape(16, 'TitleUnderline', 685800, 3900000, 3200000, 57150, C.indigo),
    textShape(2, 'TitleBox', 685800, 1700000, 7200000, 2200000, 'ctr', titlePara),
    textShape(3, 'SubBox', 685800, 4000000, 7200000, 600000, 't', subPara),
  ].join('');

  return wrapSlide(`<p:bg><p:bgPr><a:solidFill><a:srgbClr val="${C.navy}"/></a:solidFill><a:effectLst/></p:bgPr></p:bg>`, shapes);
}

function makeContentSlide(slide: Slide, idx: number): string {
  const headerColor = accent(idx);
  const hasTitle = !!slide.title;

  const bodyY = hasTitle ? 1100000 : 200000;
  const bodyCy = hasTitle ? 5500000 : 6400000;

  const bulletParagraphs = slide.bullets.map((b, bi) => {
    const bc = BULLET_COLORS[bi % BULLET_COLORS.length];
    const clean = b.replace(/^\*\*|\*\*$/g, '');
    const isBold = bi === 0;
    return `<a:p><a:pPr marL="342900" indent="-342900"><a:buClr><a:srgbClr val="${bc}"/></a:buClr><a:buFont typeface="Arial" charset="0"/><a:buChar char="&#x25B8;"/></a:pPr><a:r><a:rPr lang="en-US" sz="1800" b="${isBold?'1':'0'}" dirty="0"><a:solidFill><a:srgbClr val="${C.darkTxt}"/></a:solidFill><a:latin typeface="Calibri"/></a:rPr><a:t>${xEsc(clean)}</a:t></a:r></a:p>`;
  }).join('');

  const titlePara = hasTitle ? `<a:p><a:pPr algn="l"/><a:r><a:rPr lang="en-US" sz="2600" b="1" dirty="0"><a:solidFill><a:srgbClr val="${C.white}"/></a:solidFill><a:latin typeface="Calibri Light"/></a:rPr><a:t>${xEsc(slide.title)}</a:t></a:r></a:p>` : '';

  const shapes = [
    hasTitle ? solidShape(10, 'HeaderBar', 0, 0, 9144000, 950000, headerColor) : '',
    solidShape(11, 'LeftStripe', 0, hasTitle ? 950000 : 0, 76200, hasTitle ? 5720000 : 6858000, headerColor),
    solidShape(12, 'BottomLine', 0, 6700800, 9144000, 57150, headerColor),
    hasTitle ? textShape(2, 'TitleBox', 200000, 90000, 8900000, 770000, 'ctr', titlePara) : '',
    textShape(3, 'BodyBox', 200000, bodyY, 8900000, bodyCy, 't', bulletParagraphs || `<a:p><a:r><a:rPr lang="en-US" sz="1800" dirty="0"><a:solidFill><a:srgbClr val="${C.muted}"/></a:solidFill></a:rPr><a:t></a:t></a:r></a:p>`),
    `<p:sp><p:nvSpPr><p:cNvPr id="13" name="PageNum"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="8400000" y="6620000"/><a:ext cx="650000" cy="200000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr><p:txBody><a:bodyPr anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="r"/><a:fld id="{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}" type="slidenum"><a:rPr lang="en-US" sz="900" dirty="0"><a:solidFill><a:srgbClr val="${C.muted}"/></a:solidFill></a:rPr><a:t>‹#›</a:t></a:fld></a:p></p:txBody></p:sp>`,
  ].filter(Boolean).join('');

  return wrapSlide(`<p:bg><p:bgPr><a:solidFill><a:srgbClr val="${C.offWht}"/></a:solidFill><a:effectLst/></p:bgPr></p:bg>`, shapes);
}

function wrapSlide(bg: string, shapes: string): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld>${bg}<p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>${shapes}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`;
}

export async function downloadPptx(content: string, filename = 'fius-presentation') {
  let processedContent = content;
  try {
    const res = await fetch('/api/format-for-export', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ content, type: 'pptx' }),
    });
    if (res.ok) { const d = await res.json(); if (d.formatted) processedContent = d.formatted; }
  } catch { /* use original */ }

  const slides = parseSlides(processedContent);
  const presentationTitle = slides[0]?.title || filename.replace(/-/g, ' ');
  const slideCount = slides.length;

  type SlideEntry = { isTitleSlide: true; title: string; subtitle: string } | { isTitleSlide: false; slide: Slide; slideIndex: number };
  const allSlides: SlideEntry[] = [
    { isTitleSlide: true, title: presentationTitle, subtitle: slideCount > 1 ? `${slideCount} Sections` : 'Key Insights' },
    ...slides.map((s, i) => ({ isTitleSlide: false as const, slide: s, slideIndex: i })),
  ];

  const n = allSlides.length;

  const contentTypes = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>${allSlides.map((_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}<Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>`;

  const rootRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`;

  const presentation = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId${n+1}"/></p:sldMasterIdLst><p:sldIdLst>${allSlides.map((_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+1}"/>`).join('')}</p:sldIdLst><p:sldSz cx="9144000" cy="6858000" type="screen4x3"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`;

  const presentationRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${allSlides.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join('')}<Relationship Id="rId${n+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/></Relationships>`;

  const slideRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`;

  const slideMaster = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:bg><p:bgRef idx="1001"><a:schemeClr val="bg1"/></p:bgRef></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/><p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle><a:lstStyle><a:lvl1pPr><a:defRPr lang="en-US" sz="3600" b="1"><a:solidFill><a:srgbClr val="${C.darkTxt}"/></a:solidFill></a:defRPr></a:lvl1pPr></a:lstStyle></p:titleStyle><p:bodyStyle><a:lstStyle><a:lvl1pPr><a:defRPr lang="en-US" sz="1800"><a:solidFill><a:srgbClr val="${C.darkTxt}"/></a:solidFill></a:defRPr></a:lvl1pPr></a:lstStyle></p:bodyStyle></p:txStyles></p:sldMaster>`;

  const slideMasterRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`;

  const slideLayout = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;

  const slideLayoutRels = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`;

  const theme = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Fius"><a:themeElements><a:clrScheme name="Fius"><a:dk1><a:srgbClr val="${C.darkTxt}"/></a:dk1><a:lt1><a:srgbClr val="${C.white}"/></a:lt1><a:dk2><a:srgbClr val="${C.navy}"/></a:dk2><a:lt2><a:srgbClr val="${C.offWht}"/></a:lt2><a:accent1><a:srgbClr val="${C.indigo}"/></a:accent1><a:accent2><a:srgbClr val="${C.purple}"/></a:accent2><a:accent3><a:srgbClr val="${C.cyan}"/></a:accent3><a:accent4><a:srgbClr val="${C.emerald}"/></a:accent4><a:accent5><a:srgbClr val="${C.amber}"/></a:accent5><a:accent6><a:srgbClr val="${C.rose}"/></a:accent6><a:hlink><a:srgbClr val="${C.indigo}"/></a:hlink><a:folHlink><a:srgbClr val="${C.purple}"/></a:folHlink></a:clrScheme><a:fontScheme name="Fius"><a:majorFont><a:latin typeface="Calibri Light"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Calibri"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="Fius"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="6350"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="12700"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="19050"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`;

  const slideXmls = allSlides.map(s => {
    if (s.isTitleSlide) return makeTitleSlide(s.title, s.subtitle);
    return makeContentSlide(s.slide, s.slideIndex);
  });

  const files: ZFile[] = [
    { name: '[Content_Types].xml', data: enc(contentTypes) },
    { name: '_rels/.rels', data: enc(rootRels) },
    { name: 'ppt/presentation.xml', data: enc(presentation) },
    { name: 'ppt/_rels/presentation.xml.rels', data: enc(presentationRels) },
    { name: 'ppt/theme/theme1.xml', data: enc(theme) },
    { name: 'ppt/slideMasters/slideMaster1.xml', data: enc(slideMaster) },
    { name: 'ppt/slideMasters/_rels/slideMaster1.xml.rels', data: enc(slideMasterRels) },
    { name: 'ppt/slideLayouts/slideLayout1.xml', data: enc(slideLayout) },
    { name: 'ppt/slideLayouts/_rels/slideLayout1.xml.rels', data: enc(slideLayoutRels) },
    ...slideXmls.map((xml, i) => ({ name: `ppt/slides/slide${i+1}.xml`, data: enc(xml) })),
    ...allSlides.map((_, i) => ({ name: `ppt/slides/_rels/slide${i+1}.xml.rels`, data: enc(slideRels) })),
  ];

  const zip = buildZip(files);
  const blob = new Blob([zip], { type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = `${filename}.pptx`;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
