// AUTO-GENERATED list of recognizable subjects in the Fius Heavy app.
// Used as a hint to vision models so they can correctly identify
// uploaded images of these specific people, brands, or icons.

export const NOMAD_AI_LOGOS: string[] = [
  'ChatGPT (OpenAI) — green/black flower-like sunburst logo, often shown with the word ChatGPT or GPT',
  'Claude (Anthropic) — orange/peach flower or stylised A, often shown with the word Claude',
  'Gemini (Google) — blue-purple-pink gradient four-pointed star/sparkle, often shown with the word Gemini',
  'Perplexity AI — blue/teal stylised circular logo of two interlocking arcs, often shown with the lowercase word perplexity',
  'Grok (xAI) — black slash/cross logo by xAI, often shown with the word Grok',
  'DeepSeek — blue whale/wave icon, often shown with the words DeepSeek or DeepSeek V3',
  'Doubao (ByteDance) — colourful icon, often shown with the word Doubao',
  'Kimi (Moonshot AI) — moon-themed icon, often shown with the word Kimi',
  'Qwen (Alibaba) — orange/red icon, often shown with the word Qwen',
  'Llama 4 (Meta) — llama or geometric icon, often shown with the word Llama or Meta',
  'Mistral AI — orange/red gradient icon, often shown with the word Mistral',
  'Fius / Fius Pro — the in-app brand mark for the Fius AI assistant',
];

export const HISTORICAL_FIGURES: string[] = [
  'Muhammad Ali Jinnah (1876–1948, Founder of Pakistan)',
  'Mahatma Gandhi (1869–1948, Leader of Indian Independence)',
  'Julius Caesar (100–44 BC, Roman Dictator)',
  'Alexander the Great (356–323 BC, Macedonian Conqueror)',
  'Napoleon Bonaparte (1769–1821, French Emperor)',
  'Abraham Lincoln (1809–1865, 16th US President)',
  'Winston Churchill (1874–1965, British Prime Minister)',
  'Franklin D. Roosevelt (1882–1945, 32nd US President)',
  'Joseph Stalin (1878–1953, Soviet Leader)',
  'Mao Zedong (1893–1976, Chinese Communist Leader)',
  'Che Guevara (1928–1967, Revolutionary)',
  'Nelson Mandela (1918–2013, South African President)',
  'Genghis Khan (1162–1227, Mongol Empire Founder)',
  'Cleopatra VII (69–30 BC, Egyptian Queen)',
  'Queen Elizabeth I (1533–1603, Queen of England)',
  'Catherine the Great (1729–1796, Russian Empress)',
  'Peter the Great (1672–1725, Russian Emperor)',
  'George Washington (1732–1799, 1st US President)',
  'Thomas Jefferson (1743–1826, 3rd US President)',
  'Benjamin Franklin (1706–1790, Founding Father & Inventor)',
  'Simón Bolívar (1783–1830, South American Liberator)',
  'Fidel Castro (1926–2016, Cuban Leader)',
  'Benito Mussolini (1883–1945, Italian Dictator)',
  'Adolf Hitler (1889–1945, German Dictator)',
  'Otto von Bismarck (1815–1898, German Chancellor)',
  'Charlemagne (742–814, Frankish Emperor)',
  'Joan of Arc (1412–1431, French Military Leader)',
  'Akbar the Great (1542–1605, Mughal Emperor)',
  'Saladin (1137–1193, Sultan of Egypt & Syria)',
  'Cyrus the Great (600–530 BC, Persian Emperor)',
  'Marcus Aurelius (121–180 AD, Roman Emperor & Philosopher)',
  'Augustus Caesar (63 BC–14 AD, First Roman Emperor)',
  'Nero (37–68 AD, Roman Emperor)',
  'Hannibal Barca (247–183 BC, Carthaginian General)',
  'Boudicca (30–61 AD, British Celtic Queen)',
  'Ramesses II (1303–1213 BC, Egyptian Pharaoh)',
  'Suleiman the Magnificent (1494–1566, Ottoman Sultan)',
  'Tipu Sultan (1750–1799, Ruler of Mysore)',
  'Henry VIII (1491–1547, King of England)',
  'Mehmed II (1432–1481, Ottoman Sultan (Conqueror))',
  'Tamerlane (Timur) (1336–1405, Turco-Mongol Conqueror)',
  'Shah Jahan (1592–1666, Mughal Emperor)',
  'Ashoka the Great (304–232 BC, Mauryan Emperor)',
  'Spartacus (111–71 BC, Gladiator & Rebel Leader)',
  'Mustafa Kemal Atatürk (1881–1938, Founder of Modern Turkey)',
  'Martin Luther King Jr. (1929–1968, Civil Rights Leader)',
  'Maximilien Robespierre (1758–1794, French Revolutionary)',
  'Harriet Tubman (1822–1913, Abolitionist & Freedom Fighter)',
  'Attila the Hun (406–453, Hunnic Empire Leader)',
  'Darius the Great (550–486 BC, Persian King)',
  'Constantine the Great (272–337 AD, Roman Emperor)',
  'Socrates (470–399 BC, Greek Philosopher)',
  'Plato (428–348 BC, Greek Philosopher)',
  'Aristotle (384–322 BC, Greek Philosopher)',
  'Confucius (551–479 BC, Chinese Philosopher)',
  'Sun Tzu (544–496 BC, Chinese Strategist)',
  'Lao Tzu (6th century BC, Daoist Philosopher)',
  'Friedrich Nietzsche (1844–1900, German Philosopher)',
  'Karl Marx (1818–1883, Socialist Philosopher)',
  'John Locke (1632–1704, English Philosopher)',
  'Jean-Jacques Rousseau (1712–1778, French Philosopher)',
  'Voltaire (1694–1778, French Enlightenment Philosopher)',
  'René Descartes (1596–1650, French Philosopher)',
  'Immanuel Kant (1724–1804, German Philosopher)',
  'Georg Hegel (1770–1831, German Philosopher)',
  'Arthur Schopenhauer (1788–1860, German Philosopher)',
  'Søren Kierkegaard (1813–1855, Danish Philosopher)',
  'David Hume (1711–1776, Scottish Philosopher)',
  'Thomas Hobbes (1588–1679, English Philosopher)',
  'Baruch Spinoza (1632–1677, Dutch Philosopher)',
  'Gottfried Leibniz (1646–1716, German Philosopher)',
  'Bertrand Russell (1872–1970, British Philosopher)',
  'Epicurus (341–270 BC, Greek Philosopher)',
  'Ibn Rushd (Averroes) (1126–1198, Islamic Philosopher)',
  'Niccolò Machiavelli (1469–1527, Political Philosopher)',
  'Francis Bacon (1561–1626, English Philosopher)',
  'John Stuart Mill (1806–1873, English Philosopher)',
  'Jeremy Bentham (1748–1832, English Philosopher)',
  'Heraclitus (535–475 BC, Greek Philosopher)',
  'Democritus (460–370 BC, Greek Philosopher)',
  'Zeno of Citium (334–262 BC, Stoic Founder)',
  'Albert Einstein (1879–1955, Theoretical Physicist)',
  'Isaac Newton (1643–1727, Mathematician & Physicist)',
  'Nikola Tesla (1856–1943, Electrical Engineer & Inventor)',
  'Charles Darwin (1809–1882, Naturalist)',
  'Galileo Galilei (1564–1642, Astronomer & Physicist)',
  'Archimedes (287–212 BC, Greek Mathematician)',
  'Leonardo da Vinci (1452–1519, Polymath & Artist)',
  'Marie Curie (1867–1934, Physicist & Chemist)',
  'Stephen Hawking (1942–2018, Theoretical Physicist)',
  'Carl Sagan (1934–1996, Astronomer & Author)',
  'Richard Feynman (1918–1988, Physicist)',
  'Michael Faraday (1791–1867, Physicist & Chemist)',
  'Niels Bohr (1885–1962, Physicist)',
  'Louis Pasteur (1822–1895, Microbiologist)',
  'Alan Turing (1912–1954, Computer Scientist)',
  'Ada Lovelace (1815–1852, First Computer Programmer)',
  'Nicolaus Copernicus (1473–1543, Astronomer)',
  'Carl Friedrich Gauss (1777–1855, Mathematician)',
  'Leonhard Euler (1707–1783, Mathematician)',
  'Alexander Fleming (1881–1955, Bacteriologist)',
  'Pythagoras (570–495 BC, Greek Mathematician)',
  'Euclid (300 BC, Greek Mathematician)',
  'Gregor Mendel (1822–1884, Geneticist)',
  'Max Planck (1858–1947, Physicist)',
  'Johannes Kepler (1571–1630, Astronomer)',
  'Charles Babbage (1791–1871, Computer Pioneer)',
  'James Clerk Maxwell (1831–1879, Physicist)',
  'Hypatia (360–415 AD, Greek Mathematician & Philosopher)',
  'Al-Khwarizmi (780–850, Mathematician (Algebra\)',
  'Tycho Brahe (1546–1601, Astronomer)',
  'William Shakespeare (1564–1616, English Playwright & Poet)',
  'Edgar Allan Poe (1809–1849, American Author)',
  'Mark Twain (1835–1910, American Author)',
  'Ernest Hemingway (1899–1961, American Author)',
  'Franz Kafka (1883–1924, Czech Author)',
  'Leo Tolstoy (1828–1910, Russian Author)',
  'Fyodor Dostoevsky (1821–1881, Russian Author)',
  'Victor Hugo (1802–1885, French Author)',
  'Charles Dickens (1812–1870, English Author)',
  'Oscar Wilde (1854–1900, Irish Author)',
  'George Orwell (1903–1950, English Author)',
  'Homer (8th century BC, Greek Poet)',
  'Dante Alighieri (1265–1321, Italian Poet)',
  'Johann Wolfgang von Goethe (1749–1832, German Author)',
  'Rumi (1207–1273, Persian Sufi Poet)',
  'Omar Khayyam (1048–1131, Persian Poet & Mathematician)',
  'Michelangelo (1475–1564, Italian Artist)',
  'Vincent van Gogh (1853–1890, Dutch Painter)',
  'Pablo Picasso (1881–1973, Spanish Artist)',
  'Salvador Dalí (1904–1989, Spanish Surrealist)',
  'Ludwig van Beethoven (1770–1827, German Composer)',
  'Wolfgang Amadeus Mozart (1756–1791, Austrian Composer)',
  'Johann Sebastian Bach (1685–1750, German Composer)',
  'Jane Austen (1775–1817, English Novelist)',
  'Virginia Woolf (1882–1941, English Author)',
  'Frédéric Chopin (1810–1849, Polish Composer)',
  'Richard Wagner (1813–1883, German Composer)',
  'Claude Monet (1840–1926, French Impressionist)',
  'Rembrandt (1606–1669, Dutch Painter)',
  'Christopher Columbus (1451–1506, Explorer)',
  'Vasco da Gama (1460–1524, Portuguese Explorer)',
  'Ferdinand Magellan (1480–1521, Portuguese Explorer)',
  'Marco Polo (1254–1324, Italian Explorer)',
  'James Cook (1728–1779, British Explorer)',
  'Ibn Battuta (1304–1368, Moroccan Explorer)',
  'Zheng He (1371–1433, Chinese Explorer)',
  'Roald Amundsen (1872–1928, Norwegian Explorer)',
  'Ernest Shackleton (1874–1922, Irish-British Explorer)',
  'Malcolm X (1925–1965, Civil Rights Activist)',
  'Rosa Parks (1913–2005, Civil Rights Activist)',
  'Frederick Douglass (1818–1895, Abolitionist & Orator)',
  'Susan B. Anthony (1820–1906, Suffragette)',
  'Florence Nightingale (1820–1910, Nursing Pioneer)',
  'Emmeline Pankhurst (1858–1928, Suffragette)',
  'Eleanor Roosevelt (1884–1962, Humanitarian & First Lady)',
  'Simone de Beauvoir (1908–1986, Feminist Philosopher)',
  'Mary Wollstonecraft (1759–1797, Feminist Author)',
  'Martin Luther (1483–1546, Protestant Reformer)',
  'Thomas More (1478–1535, English Scholar & Martyr)',
  'Erasmus of Rotterdam (1466–1536, Humanist Scholar)',
  'W.E.B. Du Bois (1868–1963, Civil Rights Leader & Scholar)',
  'Harriet Beecher Stowe (1811–1896, American Author & Abolitionist)',
  'John Lennon (1940–1980, Musician & Peace Activist)',
  'Leon Trotsky (1879–1940, Russian Revolutionary)',
  'Indira Gandhi (1917–1984, Indian Prime Minister)',
  'Margaret Thatcher (1925–2013, British Prime Minister)',
];

// ===== CURRENT FAMOUS PEOPLE =====

export const HOLLYWOOD_ACTORS: string[] = [
  'Tom Cruise', 'Leonardo DiCaprio', 'Brad Pitt', 'Johnny Depp', 'Will Smith',
  'Robert Downey Jr.', 'Chris Hemsworth', 'Chris Evans', 'Chris Pratt', 'Mark Ruffalo',
  'Scarlett Johansson', 'Jennifer Lawrence', 'Emma Stone', 'Emma Watson', 'Anne Hathaway',
  'Angelina Jolie', 'Meryl Streep', 'Jennifer Aniston', 'Julia Roberts', 'Sandra Bullock',
  'Tom Hanks', 'Denzel Washington', 'Morgan Freeman', 'Samuel L. Jackson', 'Hugh Jackman',
  'Ryan Reynolds', 'Ryan Gosling', 'Matthew McConaughey', 'Christian Bale', 'Joaquin Phoenix',
  'Keanu Reeves', 'Dwayne "The Rock" Johnson', 'Jason Statham', 'Vin Diesel', 'Arnold Schwarzenegger',
  'Sylvester Stallone', 'Robert De Niro', 'Al Pacino', 'Anthony Hopkins', 'Daniel Day-Lewis',
  'Timothée Chalamet', 'Zendaya', 'Tom Holland', 'Margot Robbie', 'Florence Pugh',
  'Cillian Murphy', 'Pedro Pascal', 'Henry Cavill', 'Benedict Cumberbatch', 'Idris Elba',
  'Daniel Craig', 'Christopher Nolan', 'Steven Spielberg', 'Quentin Tarantino', 'Martin Scorsese',
  'Will Ferrell', 'Adam Sandler', 'Jim Carrey', 'Eddie Murphy', 'Kevin Hart',
];

export const BOLLYWOOD_ACTORS: string[] = [
  'Shah Rukh Khan', 'Salman Khan', 'Aamir Khan', 'Akshay Kumar', 'Hrithik Roshan',
  'Ranbir Kapoor', 'Ranveer Singh', 'Vicky Kaushal', 'Varun Dhawan', 'Sidharth Malhotra',
  'Tiger Shroff', 'Kartik Aaryan', 'Ayushmann Khurrana', 'Rajkummar Rao', 'Pankaj Tripathi',
  'Nawazuddin Siddiqui', 'Irrfan Khan', 'Anil Kapoor', 'Anupam Kher', 'Amitabh Bachchan',
  'Abhishek Bachchan', 'Saif Ali Khan', 'Ajay Devgn', 'Sanjay Dutt', 'Govinda',
  'Deepika Padukone', 'Priyanka Chopra', 'Alia Bhatt', 'Katrina Kaif', 'Kareena Kapoor',
  'Kajol', 'Madhuri Dixit', 'Aishwarya Rai Bachchan', 'Anushka Sharma', 'Vidya Balan',
  'Kangana Ranaut', 'Sonam Kapoor', 'Shraddha Kapoor', 'Kriti Sanon', 'Disha Patani',
  'Janhvi Kapoor', 'Sara Ali Khan', 'Ananya Panday', 'Tara Sutaria', 'Kiara Advani',
  'Allu Arjun', 'Prabhas', 'Mahesh Babu', 'Ram Charan', 'Jr. NTR',
  'Yash (KGF)', 'Rajinikanth', 'Kamal Haasan', 'Vijay (Thalapathy)', 'Dhanush',
  'Fahadh Faasil', 'Mohanlal', 'Mammootty', 'Samantha Ruth Prabhu', 'Rashmika Mandanna',
  'Pooja Hegde', 'Nayanthara', 'Trisha Krishnan', 'Sai Pallavi',
];

export const PAKISTANI_CELEBRITIES: string[] = [
  'Fawad Khan', 'Imran Abbas', 'Humayun Saeed', 'Mahira Khan', 'Ayeza Khan',
  'Sajal Aly', 'Hania Aamir', 'Iqra Aziz', 'Mawra Hocane', 'Saba Qamar',
  'Sanam Saeed', 'Yumna Zaidi', 'Maya Ali', 'Ayesha Omar', 'Ahad Raza Mir',
  'Bilal Abbas Khan', 'Feroze Khan', 'Danish Taimoor', 'Wahaj Ali', 'Imran Ashraf',
  'Atif Aslam', 'Ali Zafar', 'Rahat Fateh Ali Khan', 'Strings (band)', 'Junoon (band)',
  'Coke Studio Pakistan', 'Asim Azhar', 'Shae Gill', 'Aima Baig', 'Momina Mustehsan',
];

export const PAKISTANI_POLITICIANS: string[] = [
  'Imran Khan (PTI, former Prime Minister of Pakistan)',
  'Shehbaz Sharif (current Prime Minister of Pakistan, PML-N)',
  'Nawaz Sharif (3-time former PM of Pakistan, PML-N)',
  'Bilawal Bhutto Zardari (PPP Chairman, former Foreign Minister)',
  'Asif Ali Zardari (current President of Pakistan, PPP)',
  'Maryam Nawaz Sharif (Chief Minister of Punjab, Pakistan)',
  'Asim Munir (Chief of Army Staff, Pakistan)',
  'Fazlur Rehman (JUI-F leader)',
  'Sirajul Haq (Jamaat-e-Islami leader)',
  'Pervez Musharraf (former President of Pakistan)',
  'Benazir Bhutto (former Prime Minister of Pakistan)',
];

export const INDIAN_POLITICIANS: string[] = [
  'Narendra Modi (current Prime Minister of India, BJP)',
  'Amit Shah (Home Minister of India, BJP)',
  'Rahul Gandhi (Congress Leader of Opposition)',
  'Sonia Gandhi (Congress)', 'Priyanka Gandhi Vadra (Congress)',
  'Arvind Kejriwal (AAP Convenor, former CM Delhi)',
  'Yogi Adityanath (Chief Minister of Uttar Pradesh, BJP)',
  'Mamata Banerjee (Chief Minister of West Bengal, TMC)',
  'M. K. Stalin (Chief Minister of Tamil Nadu, DMK)',
  'Nitish Kumar (Chief Minister of Bihar, JDU)',
  'Droupadi Murmu (current President of India)',
  'Jagdeep Dhankhar (Vice President of India)',
  'Nirmala Sitharaman (Finance Minister of India)',
  'S. Jaishankar (External Affairs Minister of India)',
  'Rajnath Singh (Defence Minister of India)',
  'Akhilesh Yadav (Samajwadi Party)', 'Mayawati (BSP)',
];

export const WORLD_LEADERS_CURRENT: string[] = [
  'Donald Trump (47th President of the United States)',
  'Kamala Harris (former US Vice President)',
  'Joe Biden (46th President of the United States)',
  'Vladimir Putin (President of Russia)',
  'Xi Jinping (President of China)',
  'Volodymyr Zelenskyy (President of Ukraine)',
  'Emmanuel Macron (President of France)',
  'Olaf Scholz (former Chancellor of Germany)',
  'Friedrich Merz (Chancellor of Germany)',
  'Keir Starmer (Prime Minister of the United Kingdom)',
  'Rishi Sunak (former PM of the United Kingdom)',
  'King Charles III (King of the United Kingdom)',
  'Justin Trudeau (former PM of Canada)', 'Mark Carney (PM of Canada)',
  'Anthony Albanese (PM of Australia)',
  'Fumio Kishida (former PM of Japan)', 'Shigeru Ishiba (PM of Japan)',
  'Yoon Suk-yeol (former President of South Korea)',
  'Recep Tayyip Erdoğan (President of Turkey)',
  'Mohammed bin Salman / MBS (Crown Prince of Saudi Arabia)',
  'Sheikh Mohammed bin Zayed / MBZ (President of UAE)',
  'Benjamin Netanyahu (Prime Minister of Israel)',
  'Pope Francis', 'Pope Leo XIV',
  'Javier Milei (President of Argentina)',
  'Luiz Inácio Lula da Silva (President of Brazil)',
  'Claudia Sheinbaum (President of Mexico)',
  'Cyril Ramaphosa (President of South Africa)',
];

export const TECH_BUSINESS_LEADERS: string[] = [
  'Elon Musk (CEO of Tesla, SpaceX, owner of X/Twitter)',
  'Jeff Bezos (founder of Amazon, Blue Origin)',
  'Mark Zuckerberg (CEO of Meta/Facebook)',
  'Bill Gates (co-founder of Microsoft)',
  'Sundar Pichai (CEO of Google/Alphabet)',
  'Satya Nadella (CEO of Microsoft)',
  'Tim Cook (CEO of Apple)',
  'Sam Altman (CEO of OpenAI)',
  'Dario Amodei (CEO of Anthropic)',
  'Demis Hassabis (CEO of Google DeepMind)',
  'Jensen Huang (CEO of NVIDIA)',
  'Larry Page', 'Sergey Brin (Google co-founders)',
  'Larry Ellison (Oracle)', 'Michael Dell (Dell)',
  'Warren Buffett (Berkshire Hathaway)', 'Charlie Munger',
  "Mukesh Ambani (Reliance Industries, India's richest)",
  'Gautam Adani (Adani Group)',
  'Ratan Tata (Tata Group)',
  'Anand Mahindra (Mahindra Group)',
  'N. R. Narayana Murthy (Infosys co-founder)',
  'Azim Premji (Wipro)',
  'Bernard Arnault (LVMH)',
  'Jack Ma (Alibaba founder)', 'Pony Ma (Tencent)',
  'Masayoshi Son (SoftBank)',
  'Richard Branson (Virgin)',
  'Oprah Winfrey', 'Rihanna (Fenty Beauty)', 'Kylie Jenner (Kylie Cosmetics)',
];

export const MUSICIANS_CURRENT: string[] = [
  'Taylor Swift', 'Beyoncé', 'Jay-Z', 'Drake', 'Kendrick Lamar',
  'Eminem', 'Kanye West', 'Travis Scott', 'The Weeknd', 'Bad Bunny',
  'Billie Eilish', 'Olivia Rodrigo', 'Ariana Grande', 'Dua Lipa', 'Lady Gaga',
  'Rihanna', 'Bruno Mars', 'Ed Sheeran', 'Justin Bieber', 'Harry Styles',
  'Adele', 'Sabrina Carpenter', 'Chappell Roan', 'BTS', 'BLACKPINK',
  'Jung Kook', 'Jimin', 'Lisa (BLACKPINK)', 'IU',
  'Arijit Singh', 'AR Rahman', 'Diljit Dosanjh', 'Karan Aujla', 'Sidhu Moose Wala',
  'Honey Singh', 'Badshah', 'Neha Kakkar', 'Shreya Ghoshal',
];

export const ATHLETES_CURRENT: string[] = [
  'Lionel Messi', 'Cristiano Ronaldo', 'Neymar', 'Kylian Mbappé', 'Erling Haaland',
  'Vinícius Júnior', 'Jude Bellingham', 'Mohamed Salah', 'Robert Lewandowski',
  'LeBron James', 'Stephen Curry', 'Kevin Durant', 'Giannis Antetokounmpo',
  'Luka Dončić', 'Nikola Jokić', 'Jayson Tatum', 'Michael Jordan', 'Kobe Bryant',
  'Tom Brady', 'Patrick Mahomes', 'Travis Kelce',
  'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Carlos Alcaraz', 'Jannik Sinner',
  'Serena Williams', 'Coco Gauff', 'Iga Świątek',
  'Tiger Woods', 'Rory McIlroy', 'Scottie Scheffler',
  'Max Verstappen', 'Lewis Hamilton', 'Charles Leclerc', 'Lando Norris',
  'Conor McGregor', 'Khabib Nurmagomedov', 'Jon Jones', 'Israel Adesanya',
  'Floyd Mayweather', 'Canelo Álvarez', 'Tyson Fury', 'Anthony Joshua', 'Mike Tyson',
  'Virat Kohli', 'Rohit Sharma', 'MS Dhoni', 'Sachin Tendulkar', 'Jasprit Bumrah',
  'Hardik Pandya', 'Shubman Gill', 'KL Rahul', 'Rishabh Pant',
  'Babar Azam', 'Shaheen Afridi', 'Mohammad Rizwan', 'Shadab Khan', 'Naseem Shah',
  'Wasim Akram', 'Shahid Afridi', 'Shoaib Akhtar',
  'Pat Cummins', 'Steve Smith', 'David Warner', 'Joe Root', 'Ben Stokes',
  'Kane Williamson', 'AB de Villiers',
  'Simone Biles', 'Usain Bolt', 'Michael Phelps',
];

export const INTERNET_CELEBRITIES: string[] = [
  'MrBeast (Jimmy Donaldson)', 'PewDiePie', 'Logan Paul', 'Jake Paul', 'KSI',
  'Kim Kardashian', 'Kourtney Kardashian', 'Khloé Kardashian', 'Kris Jenner', 'Kendall Jenner',
  'Andrew Tate', 'Joe Rogan', 'Lex Fridman', 'Gary Vaynerchuk', 'Alex Hormozi',
  'iShowSpeed', 'Mark Rober', 'CarryMinati (Ajey Nagar)', 'Bhuvan Bam', 'Ashish Chanchlani',
  'Amit Bhadana', 'Sandeep Maheshwari', 'Ranveer Allahbadia (BeerBiceps)',
];

export function buildRecognitionHint(): string {
  return [
    'KNOWN SUBJECTS HINT — the user may upload images of any of the following. If the visual evidence (text in the image, distinctive shape, recognisable face) clearly matches one of these, name it. If it does NOT clearly match, do NOT force a match — describe honestly.',
    '',
    'AI MODEL LOGOS in this app:',
    NOMAD_AI_LOGOS.map(s => '- ' + s).join('\n'),
    '',
    'HISTORICAL FIGURES the user may upload portraits of:',
    HISTORICAL_FIGURES.map(s => '- ' + s).join('\n'),
    '',
    'CURRENT WORLD LEADERS & POLITICIANS:',
    [...WORLD_LEADERS_CURRENT, ...INDIAN_POLITICIANS, ...PAKISTANI_POLITICIANS].map(s => '- ' + s).join('\n'),
    '',
    'BUSINESS / TECH LEADERS & BILLIONAIRES:',
    TECH_BUSINESS_LEADERS.map(s => '- ' + s).join('\n'),
    '',
    'HOLLYWOOD ACTORS & FILMMAKERS:',
    HOLLYWOOD_ACTORS.map(s => '- ' + s).join('\n'),
    '',
    'BOLLYWOOD & INDIAN FILM CELEBRITIES (Hindi, Telugu, Tamil, Malayalam):',
    BOLLYWOOD_ACTORS.map(s => '- ' + s).join('\n'),
    '',
    'PAKISTANI ACTORS, MUSICIANS & TV STARS:',
    PAKISTANI_CELEBRITIES.map(s => '- ' + s).join('\n'),
    '',
    'GLOBAL & DESI MUSICIANS:',
    MUSICIANS_CURRENT.map(s => '- ' + s).join('\n'),
    '',
    'CURRENT ATHLETES (football, cricket, NBA, tennis, F1, MMA, boxing, etc.):',
    ATHLETES_CURRENT.map(s => '- ' + s).join('\n'),
    '',
    'INTERNET CELEBRITIES & INFLUENCERS:',
    INTERNET_CELEBRITIES.map(s => '- ' + s).join('\n'),
  ].join('\n');
}
