import { cn } from "@/lib/utils";
import { useMemo, useRef, useState, useEffect } from "react";
import { useTheme } from "./theme-provider";
import {
  getLogoStyleForConversation,
  type LogoStyle,
} from "@/lib/appearance-settings";
import ringLogoLight from "@assets/fius_logo_2_white_theme_1785057130970.png";
import ringLogoDark from "@assets/fius_logo_2_dark_theme__1785057130968.png";

interface LogoProps {
  className?: string;
  size?: "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";
  lineOnly?: boolean;
  ringColor?: string;
  ringOpacity?: number;
  letterColor?: string;
}

/**
 * Both the wavy path and the circle path are generated by the same formula.
 * When amp=0  → perfect smooth circle (all points at radius R)
 * When amp>0  → scalloped wavy circle (points alternate inner / outer)
 * Because the command structure is identical, SVG SMIL can interpolate between them.
 */
function makeWavyPath(cx: number, cy: number, R: number, waves: number, amp: number): string {
  const numPts = waves * 2;
  const pts: [number, number][] = [];
  for (let i = 0; i < numPts; i++) {
    const angle = (2 * Math.PI * i / numPts) - Math.PI / 2;
    const r = R + (i % 2 === 0 ? amp : -amp);
    pts.push([cx + r * Math.cos(angle), cy + r * Math.sin(angle)]);
  }
  const mid = (i: number): [number, number] => [
    (pts[i][0] + pts[(i + 1) % numPts][0]) / 2,
    (pts[i][1] + pts[(i + 1) % numPts][1]) / 2,
  ];
  const start = mid(numPts - 1);
  let d = `M ${start[0].toFixed(2)} ${start[1].toFixed(2)} `;
  for (let i = 0; i < numPts; i++) {
    const m = mid(i);
    d += `Q ${pts[i][0].toFixed(2)} ${pts[i][1].toFixed(2)} ${m[0].toFixed(2)} ${m[1].toFixed(2)} `;
  }
  return d + "Z";
}

export function Logo({ className, size = "md", lineOnly = false, ringColor, ringOpacity, letterColor }: LogoProps) {
  const px    = { sm: 36, md: 46, lg: 70, xl: 86, '2xl': 130, '3xl': 190, '4xl': 260 }[size];
  const font  = { sm: 19, md: 24, lg: 36, xl: 44, '2xl': 62,  '3xl': 90,  '4xl': 124 }[size];
  const sw    = { sm: 1.6, md: 2.0, lg: 2.6, xl: 3.2, '2xl': 4.0, '3xl': 5.0, '4xl': 6.0 }[size];
  const waves = { sm: 10,  md: 11,  lg: 14,  xl: 16,  '2xl': 20,  '3xl': 24,  '4xl': 28  }[size];
  const amp   = { sm: 2.3, md: 2.7, lg: 3.8, xl: 4.8, '2xl': 6.0, '3xl': 8.0, '4xl': 10.0 }[size];
  const cx = px / 2;
  const cy = px / 2;
  const R  = px / 2 - sw - 2;

  const wavyPath   = useMemo(() => makeWavyPath(cx, cy, R, waves, amp), [cx, cy, R, waves, amp]);
  const circlePath = useMemo(() => makeWavyPath(cx, cy, R, waves, 0),   [cx, cy, R, waves]);

  const morphValues     = [circlePath, wavyPath, wavyPath, circlePath, circlePath, wavyPath].join(";");
  const morphKeyTimes   = "0; 0.18; 0.42; 0.58; 0.82; 1";
  const morphKeySplines = "0.42 0 0.58 1; 0.25 0 0.25 1; 0.42 0 0.58 1; 0.25 0 0.25 1; 0.42 0 0.58 1";

  const containerRef = useRef<HTMLDivElement>(null);

  const handleClick = () => {
    const el = containerRef.current;
    if (!el) return;
    el.style.animation = 'none';
    void el.offsetWidth;
    el.style.animation = 'fius-logo-spin360 0.65s cubic-bezier(0.23, 1, 0.32, 1) forwards';
  };

  return (
    <>
      <style>{`@keyframes fius-logo-spin360 { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
      <div
        ref={containerRef}
        className={cn(
          "relative inline-flex items-center justify-center flex-shrink-0 cursor-pointer select-none",
          className
        )}
        style={{ width: px, height: px }}
        data-testid="logo-fius"
        onClick={handleClick}
      >
        <svg
          width={px} height={px}
          viewBox={`0 0 ${px} ${px}`}
          style={{ position: "absolute", inset: 0 }}
          overflow="visible"
        >
          <path
            fill="none"
            stroke={ringColor ?? "currentColor"}
            strokeWidth={sw}
            strokeLinejoin="round"
            strokeLinecap="round"
            className="fius-logo-ring"
            style={ringOpacity !== undefined ? { strokeOpacity: ringOpacity } : undefined}
            d={circlePath}
          >
            <animate
              attributeName="d"
              values={morphValues}
              keyTimes={morphKeyTimes}
              keySplines={morphKeySplines}
              dur="8s"
              repeatCount="indefinite"
              calcMode="spline"
            />
            <animateTransform
              attributeName="transform"
              type="rotate"
              from={`0 ${cx} ${cy}`}
              to={`360 ${cx} ${cy}`}
              dur="10s"
              repeatCount="indefinite"
              calcMode="linear"
              additive="sum"
            />
          </path>

          {!lineOnly && (
            <text
              x={cx + Math.round(font * 0.06)}
              y={cy - Math.round(font * 0.06)}
              textAnchor="middle"
              dominantBaseline="central"
              fontSize={font}
              fontWeight="400"
              fontFamily="Georgia, 'Times New Roman', serif"
              fill={letterColor ?? "currentColor"}
              className="fius-logo-letter"
              style={{ userSelect: "none" }}
            >
              ƒ
            </text>
          )}
        </svg>
      </div>
    </>
  );
}

interface FiusLogoProps extends LogoProps {
  conversationId?: string;
  styleOverride?: LogoStyle;
  /** When set, wraps the SVG logo in a scale transform — ignored for rings style */
  scaleWhenCurrent?: string;
}

/**
 * The app-wide Fius mark. "current" keeps the original SVG logo, while
 * "rings" uses the supplied light/dark PNG pair with a gentle continuous spin.
 */
export function FiusLogo({
  conversationId,
  styleOverride,
  className,
  size = "md",
  scaleWhenCurrent,
  ...props
}: FiusLogoProps) {
  const { theme } = useTheme();
  const [style, setStyle] = useState<LogoStyle>(() =>
    styleOverride || getLogoStyleForConversation(conversationId)
  );

  useEffect(() => {
    const refresh = () => {
      setStyle(styleOverride || getLogoStyleForConversation(conversationId));
    };
    window.addEventListener("logoStyleChanged", refresh);
    window.addEventListener("settingsSaved", refresh);
    return () => {
      window.removeEventListener("logoStyleChanged", refresh);
      window.removeEventListener("settingsSaved", refresh);
    };
  }, [conversationId, styleOverride]);

  useEffect(() => {
    setStyle(styleOverride || getLogoStyleForConversation(conversationId));
  }, [conversationId, styleOverride]);

  if (style !== "rings") {
    const svgLogo = <Logo {...props} size={size} className={className} />;
    if (scaleWhenCurrent) {
      return <div style={{ transform: scaleWhenCurrent, transformOrigin: 'center' }}>{svgLogo}</div>;
    }
    return svgLogo;
  }

  // sm/md get a slight size boost so rings don't look congested; xl/2xl get a bigger boost for welcome screen
  const px = { sm: 46, md: 58, lg: 70, xl: 108, "2xl": 162, "3xl": 190, "4xl": 260 }[size];
  const resolvedTheme = theme === "system"
    ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
    : theme;
  const asset = resolvedTheme === "dark" ? ringLogoLight : ringLogoDark;

  const font  = { sm: 19, md: 24, lg: 36, xl: 44, '2xl': 62, '3xl': 90, '4xl': 124 }[size];

  return (
    <>
      <style>{`
        @keyframes fius-uploaded-rings-rotate {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .fius-uploaded-rings-spin {
          animation: fius-uploaded-rings-rotate 10s linear infinite;
        }
        @media (prefers-reduced-motion: reduce) {
          .fius-uploaded-rings-spin { animation: none; }
        }
      `}</style>
      <div
        className={cn("inline-flex flex-shrink-0 items-center justify-center relative", className)}
        style={{ width: px, height: px }}
        data-testid="logo-fius-rings"
      >
        {/* Rings image — rotates; no F in this PNG */}
        <img
          src={asset}
          alt=""
          aria-hidden="true"
          width={px}
          height={px}
          className="absolute inset-0 object-contain fius-uploaded-rings-spin"
          style={{ width: px, height: px }}
        />
        {/* Accent colour overlay — tints the rings via mix-blend-mode:color */}
        <div
          className="fius-rings-accent-tint absolute inset-0 pointer-events-none"
          style={{ zIndex: 1, borderRadius: '50%' }}
        />
        {/* F letter — stays static, above the tint overlay */}
        <span
          aria-label="Fius"
          style={{
            position: "relative",
            zIndex: 2,
            fontSize: font * 0.72,
            fontWeight: 400,
            fontFamily: "Georgia, 'Times New Roman', serif",
            lineHeight: 1,
            userSelect: "none",
            color: "currentColor",
            marginTop: `-${Math.round(font * 0.13)}px`,
            marginLeft: `${Math.round(font * 0.06)}px`,
          }}
        >
          ƒ
        </span>
      </div>
    </>
  );
}
