import { cn } from "@/lib/utils";
import { useMemo, useRef } from "react";

interface LogoProps {
  className?: string;
  size?: "sm" | "md" | "lg" | "xl" | "2xl" | "3xl" | "4xl";
  lineOnly?: boolean;
}

/**
 * Both the wavy path and the circle path are generated by the same formula.
 * When amp=0  → perfect smooth circle (all points at radius R)
 * When amp>0  → scalloped wavy circle (points alternate inner / outer)
 * Because the command structure is identical, SVG SMIL can interpolate between them.
 */
function makeWavyPath(cx: number, cy: number, R: number, waves: number, amp: number): string {
  const numPts = waves * 2;
  const pts: [number, number][] = [];
  for (let i = 0; i < numPts; i++) {
    const angle = (2 * Math.PI * i / numPts) - Math.PI / 2;
    const r = R + (i % 2 === 0 ? amp : -amp);
    pts.push([cx + r * Math.cos(angle), cy + r * Math.sin(angle)]);
  }
  const mid = (i: number): [number, number] => [
    (pts[i][0] + pts[(i + 1) % numPts][0]) / 2,
    (pts[i][1] + pts[(i + 1) % numPts][1]) / 2,
  ];
  const start = mid(numPts - 1);
  let d = `M ${start[0].toFixed(2)} ${start[1].toFixed(2)} `;
  for (let i = 0; i < numPts; i++) {
    const m = mid(i);
    d += `Q ${pts[i][0].toFixed(2)} ${pts[i][1].toFixed(2)} ${m[0].toFixed(2)} ${m[1].toFixed(2)} `;
  }
  return d + "Z";
}

export function Logo({ className, size = "md", lineOnly = false }: LogoProps) {
  const px    = { sm: 36, md: 46, lg: 70, xl: 86, '2xl': 130, '3xl': 190, '4xl': 260 }[size];
  const font  = { sm: 19, md: 24, lg: 36, xl: 44, '2xl': 62,  '3xl': 90,  '4xl': 124 }[size];
  const sw    = { sm: 1.6, md: 2.0, lg: 2.6, xl: 3.2, '2xl': 4.0, '3xl': 5.0, '4xl': 6.0 }[size];
  const waves = { sm: 10,  md: 11,  lg: 14,  xl: 16,  '2xl': 20,  '3xl': 24,  '4xl': 28  }[size];
  const amp   = { sm: 2.3, md: 2.7, lg: 3.8, xl: 4.8, '2xl': 6.0, '3xl': 8.0, '4xl': 10.0 }[size];
  const cx = px / 2;
  const cy = px / 2;
  const R  = px / 2 - sw - 2;

  const wavyPath   = useMemo(() => makeWavyPath(cx, cy, R, waves, amp), [cx, cy, R, waves, amp]);
  const circlePath = useMemo(() => makeWavyPath(cx, cy, R, waves, 0),   [cx, cy, R, waves]);

  const morphValues     = [circlePath, circlePath, wavyPath, wavyPath, circlePath, circlePath].join(";");
  const morphKeyTimes   = "0; 0.44; 0.62; 0.76; 0.94; 1";
  const morphKeySplines = "0.42 0 0.58 1; 0.25 0 0.25 1; 0.42 0 0.58 1; 0.25 0 0.25 1; 0.42 0 0.58 1";

  const containerRef = useRef<HTMLDivElement>(null);

  const handleClick = () => {
    const el = containerRef.current;
    if (!el) return;
    el.style.animation = 'none';
    void el.offsetWidth;
    el.style.animation = 'fius-logo-spin360 0.65s cubic-bezier(0.23, 1, 0.32, 1) forwards';
  };

  return (
    <>
      <style>{`@keyframes fius-logo-spin360 { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
      <div
        ref={containerRef}
        className={cn(
          "relative inline-flex items-center justify-center flex-shrink-0 cursor-pointer select-none",
          className
        )}
        style={{ width: px, height: px }}
        data-testid="logo-fius"
        onClick={handleClick}
      >
        <svg
          width={px} height={px}
          viewBox={`0 0 ${px} ${px}`}
          style={{ position: "absolute", inset: 0 }}
          overflow="visible"
        >
          <path
            fill="none"
            stroke="currentColor"
            strokeWidth={sw}
            strokeLinejoin="round"
            strokeLinecap="round"
            strokeOpacity={0.58}
          >
            <animate
              attributeName="d"
              values={morphValues}
              keyTimes={morphKeyTimes}
              keySplines={morphKeySplines}
              dur="8s"
              repeatCount="indefinite"
              calcMode="spline"
            />
            <animateTransform
              attributeName="transform"
              type="rotate"
              from={`0 ${cx} ${cy}`}
              to={`360 ${cx} ${cy}`}
              dur="10s"
              repeatCount="indefinite"
              calcMode="linear"
              additive="sum"
            />
          </path>

          {!lineOnly && (
            <text
              x={cx + Math.round(font * 0.06)}
              y={cy - Math.round(font * 0.06)}
              textAnchor="middle"
              dominantBaseline="central"
              fontSize={font}
              fontWeight="400"
              fontFamily="Georgia, 'Times New Roman', serif"
              fill="currentColor"
              style={{ userSelect: "none" }}
            >
              ƒ
            </text>
          )}
        </svg>
      </div>
    </>
  );
}
